### ISSUE TITLE
Breaks Watch

### ISSUE THREAD

**Issue by iammerrick** [domenic/grunt-global-wrap#1]
Breaks the typical grunt watch workflow because it creates a temporary file in the same directory as the source files which results in an infinite loop.

**Comment by domenic** [comment]
What would you suggest instead?

**Comment by domenic** [comment]
@iammerrick seriously, would love suggestions. Does watch exclude files that start with a `.`, perhaps?

I guess I could try putting it in the temp folder. Not sure if that'll work, but if it does, that'd be cool.
